theme:
  name: "material"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
site_name: UPF APIs - Aulas

nav:
  - Home: index.md
  - Aula 1 VMs e Containers:
    - Containers vs VMs: aula1/containers-vs-vms.md
    - Docker: aula1/docker.md
  - Aula 2 APIs e Microsserviços:
    - APIs: aula2/apis.md
    - Exemplo Prático de API: aula2/exemplo-api.md
    - Arquitetura de Microsserviços: aula2/arquitetura-de-microsservicos.md
  - Aula 3 SOLID:
    - Tutorial Payment API: aula3/tutorial-payment-api.md
    - Princípios SOLID: aula3/solid.md
  - Aula 4 API Gateway:
    - API Gateway: aula4/api-gateway.md
    - Tutorial API Gateway: aula4/tutorial-api-gateway.md
  - Aula 5 Message Brokers:
    - Message Brokers: aula5/message-brokers.md
    - Tutorial Event Pattern: aula5/tutorial-pub-sub-event-pattern.md
    - Tutorial RPC Pattern: aula5/tutorial-pub-sub-rpc.md
